namespace: app
service:
  name: cr-auth-service
  port: 10000
  replicas: 3
  image:
    path: docker.io/bharathpantala/santhosh-app
    tag: latest

ingress:
  enabled: false
  host: santhoshapp.gitkloud.com
  path: "/*"

service_monitor:
  enabled: true

environments:
  log_level: DEBUG

health:
  endpoint: /actuator/health
  livenessProbe:
    initialDelaySeconds: 120
    timeoutSeconds: 15
    periodSeconds: 30
    failureThreshold: 3
  readinessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 15
    periodSeconds: 30
    failureThreshold: 10
