namespace: app
service:
  name: cr-auth-service
  port: 10000
  replicas: 10
  image:
    path: 975049893517.dkr.ecr.us-east-1.amazonaws.com/dev/cr-auth-service
    tag: "1.0.0"

ingress:
  enabled: true
  host: devapps.gitkloud.com
  path: "/cr"

service_monitor:
  enabled: true

environments:
  log_level: DEBUG

health:
  endpoint: /actuator/health
  livenessProbe:
    initialDelaySeconds: 120
    timeoutSeconds: 15
    periodSeconds: 30
    failureThreshold: 3
  readinessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 15
    periodSeconds: 30
    failureThreshold: 10
